### ISSUE TITLE
Cannot launch example: "configAction.fail is not a function"

### ISSUE THREAD

**Issue by gingermike** [ag-grid/ag-grid-openfin-example#1]
Hi,

Running node @ 11.10.1, npm @ 6.7.0 on Ubuntu 18.04. 

When running the simple-grid example, I get the following output from the command line:

```
> ag-grid-openfin@0.0.0 simple-grid /home/trpgh54/work/ag-grid-openfin-example
> openfin --launch --config public/app-simple-grid.json

/home/trpgh54/work/ag-grid-openfin-example/node_modules/openfin-cli/index.js:143
        }, config).fail(function(err) {
                   ^

TypeError: configAction(...).fail is not a function
    at /home/trpgh54/work/ag-grid-openfin-example/node_modules/openfin-cli/index.js:143:20
    at suppressedCallback (fs.js:204:5)
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ag-grid-openfin@0.0.0 simple-grid: `openfin --launch --config public/app-simple-grid.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ag-grid-openfin@0.0.0 simple-grid script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trpgh54/.npm/_logs/2019-03-04T14_24_50_226Z-debug.log

```

Debug log output:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'simple-grid' ]
2 info using npm@6.7.0
3 info using node@v11.10.1
4 verbose run-script [ 'presimple-grid', 'simple-grid', 'postsimple-grid' ]
5 info lifecycle ag-grid-openfin@0.0.0~presimple-grid: ag-grid-openfin@0.0.0
6 info lifecycle ag-grid-openfin@0.0.0~simple-grid: ag-grid-openfin@0.0.0
7 verbose lifecycle ag-grid-openfin@0.0.0~simple-grid: unsafe-perm in lifecycle true
8 verbose lifecycle ag-grid-openfin@0.0.0~simple-grid: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/trpgh54/work/ag-grid-openfin-example/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle ag-grid-openfin@0.0.0~simple-grid: CWD: /home/trpgh54/work/ag-grid-openfin-example
10 silly lifecycle ag-grid-openfin@0.0.0~simple-grid: Args: [ '-c',
10 silly lifecycle   'openfin --launch --config public/app-simple-grid.json' ]
11 silly lifecycle ag-grid-openfin@0.0.0~simple-grid: Returned: code: 1  signal: null
12 info lifecycle ag-grid-openfin@0.0.0~simple-grid: Failed to exec simple-grid script
13 verbose stack Error: ag-grid-openfin@0.0.0 simple-grid: `openfin --launch --config public/app-simple-grid.json`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:984:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid ag-grid-openfin@0.0.0
15 verbose cwd /home/trpgh54/work/ag-grid-openfin-example
16 verbose Linux 4.15.0-39-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "simple-grid"
18 verbose node v11.10.1
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error ag-grid-openfin@0.0.0 simple-grid: `openfin --launch --config public/app-simple-grid.json`
22 error Exit status 1
23 error Failed at the ag-grid-openfin@0.0.0 simple-grid script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by iamorlando** [comment]
I get the same error
